### ISSUE TITLE
POT Revision Date is not updated

### ISSUE THREAD

**Issue by rahulnever2far** [rasmusbe/gulp-wp-pot#13]
Revision Date is not updated in the generated POT file.

It is always `"PO-Revision-Date: 2015-MO-DA HO:MI+ZONE\n"`.

**Comment by rasmusbe** [comment]
Since I don't compare the old version with the new one it would mean that it would update every time a change in a PHP file is detected (even if no translation changes is made).

This would be a problem in a version controlled environment, where you don't want to see unnecessary changes.

If you or anyone else have a fix for this I would gladly accept it, but I don't think I can implement it now without a major rewrite.

**Comment by frozzare** [comment]
It's this really a problem? The po editor that use the pot file is adding the right date to `PO-Revision-Date`. A pot template file is not required to have this, and maybe shouldn't have this since it says `PO` and not `POT` like `POT-Creation-Date` does.

The year is update each time you run the gulp task, so when it's 2016 it will say 2016 instead of 2015.

**Comment by rasmusbe** [comment]
I think you are right @frozzare .
