### ISSUE TITLE
2.0 breaks compatibility with Twig files

### ISSUE THREAD

**Issue by sftsk** [rasmusbe/gulp-wp-pot#38]
Hello and thank you for your great plugin!
Unfortunately with the rewrite onto 2.0 it does not work anymore for twig files.
We are using Timber in our themes and this plugin was great in combination with it.

In our newest base theme we gave up on gulp and went straight to npm trying out https://github.com/rasmusbe/wp-pot and out of a sudden it would not find any strings in twig files anymore :(

Could you please have a look? Would be wonderful to get the functionality back as there isn't really any alternative available.

Keep up the great work!

**Comment by rasmusbe** [comment]
I'm sorry but since I don't use twig myself it would be hard for me to maintain the twig-parsing.
And I really don't like the regex-method used in 1.0.

If someone wants to add twig support, feel free to do so (as a new project or via pull request to wp-pot repository) but I am not able to do it myself.

For now I recommend you to use 1.0. 
If something critical breaks in the future I might be able to release a new 1.x version.

**Comment by sftsk** [comment]
:( that is a pity to hear as there doesn't seem to be a pure npm version based on the 1.0 code.
Will see if I can figure out what code needs to be changed. Any pointers on where to look?

**Comment by rasmusbe** [comment]
Try `npm install gulp-wp-pot@^1.3`
